extensions:
  health_check: {}
receivers:
  otlp:
    protocols:
      grpc:
processors:
  batch:
exporters:
  logging:
    logLevel: $LOG_EXPORTER_LOG_LEVEL
  newrelic:
    apikey: $NEW_RELIC_API_KEY
service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [logging, newrelic]
    traces:
      receivers: [otlp]
      exporters: [logging, newrelic]
    # TODO: add log exporter once available
    # logs:
    #   receivers: [otlp]
    #   exporters: [logging, newrelic]
